### ISSUE TITLE
Arc can't install extension

### ISSUE THREAD

**Issue by glebushkaa** [stepanenko3/chrome-translation-extension#1]
The problem is that my Arc can't find manifest if I choose whole extension folder
It only can be added if I choose dist folder, but extension will not work

**Comment by stepanenko3** [comment]
Hi, @glebushkaa 
Just use extension from [Chrome App Store ](https://chromewebstore.google.com/detail/selected-text-translator/mingclglgipalelhbgbciafmdhdncikk)
